### ISSUE TITLE
How to fix install error?

### ISSUE THREAD

**Issue by csic21** [Guidewire/fern-ginkgo-client#5]
go get -u github.com/guidewire/fern-ginkgo-client 

go: github.com/guidewire/fern-ginkgo-client@upgrade (v0.0.0-20240328181530-12e33ed4ffb4) requires github.com/guidewire/fern-ginkgo-client@v0.0.0-20240328181530-12e33ed4ffb4: parsing go.mod:
        module declares its path as: client
                but was required as: github.com/guidewire/fern-ginkgo-client

**Comment by mailprak** [comment]
resolved. The path is updated.

**Comment by anoop2811** [comment]
Thank you for reporting @csic21 ! This project just started, so bear with us as we fix the nagging issues as we lead to the first release

**Comment by anoop2811** [comment]
@csic21 , I am closing this issue for now, but please feel free to comment or open a new issue if you are still facing any issue
